### PR TITLE
[TASK] Allow TYPO3 8.7

### PR DESCRIPTION
**Pull request by maddy2101**

### CODE REVIEW

**Comment by maddy2101** [comment]
in preparation of the LTS release - pretty please?

**Comment by helhum** [comment]
> in preparation of the LTS release

So we can be sure no breaking change will appear? Did you test against current master?

**Comment by maddy2101** [comment]
for the first part of the question: as we are in stab phase, I expect no further breaking changes.
for the second part: yes, my setup features master, and until now I encountered no issues.

**Comment by maddy2101** [comment]
thanks

**Pull request merged**
