### PR TITLE
[BUGFIX] Bring back checkbox pathoverride

### PR DESCRIPTION
**Pull request by Mabahe**

### CODE REVIEW

**Comment by helhum** [comment]
can you give me some context information why this is missing and why the patch works for which TYPO3 version? thanks

**Comment by helhum** [comment]
@Mabahe ping

**Comment by Mabahe** [comment]
Change is for 7+, but works also on 6. The checkbox is missing because of this chance https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.4/Deprecation-67737-TcaDropAdditionalPalette.html. Normally there should be a migration, but this seems not to work in this case. If I remember right, there was a problem, when the field, the field with the old palette definition is added to, is already in a palette. Before the patch 
screenshot_20160914_220706
After:
screenshot_20160914_220755

**Comment by helhum** [comment]
thx!

**Pull request merged**
